name: Dependency Update Bot

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  schedule:
    - cron: "0 0 */3 * *"
  workflow_dispatch:

jobs:
  update-deps:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Install dependencies
        run: npm install

      - name: Update dependencies
        run: npm update

      - name: Check for changes
        id: changes
        run: |
          git diff --quiet || echo "changed=true" >> $GITHUB_OUTPUT

      - name: Commit and push updates
        if: steps.changes.outputs.changed == 'true'
        run: |
          git config --global user.name "Asad-bot07"
          git config --global user.email "asadhussain2408@gmail.com"
          git add .
          git commit -m "chore: automated dependency update"
          git push
